from __future__ import annotations

LAMBDA_SEARCH_MIN = 1e-6
LAMBDA_SEARCH_MAX = 1e6
ADAPTIVE_PATH_MAX_CANDIDATES = 40
ADAPTIVE_PATH_MAX_ROUNDS = 4
ADAPTIVE_PATH_REFINE_PER_ROUND = 5
ADAPTIVE_PATH_TRANSITION_PROBE_MAX_CANDIDATES = 3
ADAPTIVE_PATH_PARTITION_POOL_MAX_CANDIDATES = 18
ADAPTIVE_PATH_PARTITION_POOL_MAX_ROUNDS = 2
ADAPTIVE_PATH_PARTITION_POOL_REFINE_PER_ROUND = 3
ADAPTIVE_PATH_PARTITION_POOL_TRANSITION_PROBE_MAX_CANDIDATES = 2
ADAPTIVE_PATH_LOG10_WIDTH_TOL = 0.05
ADAPTIVE_PATH_VALUE_CURVE_TOL = 1e-4
ADAPTIVE_PATH_FULL_FUSION_MAX_ITER = 80
ADAPTIVE_FIRST_PASS_OUTER_MAX_ITER = 40
ADAPTIVE_FIRST_PASS_INNER_MAX_ITER = 60
ENABLE_LIKELIHOOD_PARTITION_CANDIDATES = True
LIKELIHOOD_PARTITION_K_MAX = 50
LIKELIHOOD_PARTITION_K_ANCHORS = (1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 15, 20, 25, 30, 40, 50)
LIKELIHOOD_PARTITION_MAX_CANDIDATES_PER_K = 5
LIKELIHOOD_PARTITION_CEM_MAX_ITER = 8
LIKELIHOOD_PARTITION_REFIT_MAX_ITER = 32
LIKELIHOOD_PARTITION_SENTINEL_LAMBDA = -1.0
